version: "3.7"

services:

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=chily-user
      - POSTGRES_PASSWORD=test
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  redis:
    image: redis:8.2
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"

  web:
    build: .
    restart: on-failure
    command: node dist/main.js
    environment:
      - PORT=5000
      - SESSION_SECRET=test
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
      - DATABASE_URL=postgresql://chily-user:test@postgres:5432/chily_production
    ports:
      - "5000:5000"

volumes:
  postgres-data:
  redis-data: