# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Frontend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:20.19

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install top level dependencies
        run: yarn --frozen-lockfile
      - name: Copy shared code
        run: make copy-shared

      - name: Install frontend dependencies
        run: cd frontend && yarn install --frozen-lockfile
      - name: Test frontend
        run: cd frontend && yarn test
